### ISSUE TITLE
Add GPT response as text aswell

### ISSUE THREAD

**Issue by lesmnif** [vocodedev/vocode-react-sdk#2]
For my use case (and I think It's going to be a common thing in more use cases), I also need the response from GPT to be returned in text format or else a transcript of the conversation. I was wondering if it would be possible to work on this feature, it would be such a nice addition!

Thanks for your time, awesome repo so far!

**Comment by ajar98** [comment]
hey @lesmnif let's brainstorm options here. Should the current output text be exposed as a variable in the output of the `useConversation` hook? Any other ideas for how the output text should be served?

- we can probably expose an endpoint that contains the transcript of the conversation given conversation ID.

**Comment by lesmnif** [comment]
That sounds great!

Exposing the output text on a variable returned by the `useConversation` hook seems like the most natural solution to me.

Please let me know if any more thoughts on the matter are needed!

**Comment by HHousen** [comment]
Support for this was added in #7. Pass `subscribeTranscript: true` to the `useConversation` hook. Then, the transcript text will be exposed as a variable. See [here in the vocode-react-demo](https://github.com/vocodedev/vocode-react-demo/blob/main/src/components/Conversation.tsx#L23) repo.
