### ISSUE TITLE
Chunk size not taking effect in SelfHostedConversationConfig

### ISSUE THREAD

**Issue by TianqiYe** [vocodedev/vocode-react-sdk#6]
Original issue :  AssemblyAITranscriber was not working in the client backend, and error I got was {'error': 'Audio duration is too short'}

after a discussion with ajay he mentioned this is caused by the chunk size being too small.

after adding in this change (as ajay suggested) to https://github.com/vocodedev/vocode-react-sdk/blob/main/src/hooks/conversation.ts#L324

`} else if ("inputAudioConfig" in startMessage) {
      timeSlice = Math.round(
        (1000 * startMessage.inputAudioConfig.chunkSize) /
          startMessage.inputAudioConfig.samplingRate
      );
}`

now backend is able to consume larger chunk size so AssemblyAITranscriber can be used.

**Comment by ajar98** [comment]
this is solved in the most recent version! we buffer in the Transcriber until the audio chunk is at least 100ms longer.
